CREATE DATABASE IF NOT EXISTS PDF;
USE PDF;
CREATE TABLE IF NOT EXISTS PDFFile(
  FileID int PRIMARY KEY AUTO_INCREMENT
 ,Name varchar(50)
 ,Author varchar(50)
 ,URL varchar(255)
);
CREATE TABLE IF NOT EXISTS PDFHistory(
  HistoryID int NOT NULL PRIMARY KEY AUTO_INCREMENT
 ,BookID int 
 ,Created Date
 ,FOREIGN KEY (BookID) REFERENCES PDFFile(FileID)
);
commit;
